package com.gmwapp.hi_dude.constants


object DConstants {
    const val COUNTRY_CODE: String = "country_code"
    const val MOBILE_NUMBER: String = "mobile_number"
    const val OTP: String = "otp"
    const val GENDER: String = "gender"
    const val AGE: String = "age"
    const val INTERESTS: String = "interests"
    const val AUDIO_FILE: String = "audio"
    const val SUMMARY: String = "summary"
    const val MALE: String = "male"
    const val FEMALE: String = "female"
    const val LOGIN_ERROR = "login_error"
    const val NO_NETWORK = "no_network"
    const val TEXT = "text"
    const val AVATAR_ID = "avatar_id"
    const val LANGUAGE = "language"
    const val AUDIO = "audio"
    const val VIDEO = "video"
    const val CALL_TYPE = "call_type"
    const val IMAGE = "image"
    const val USER_ID = "user_id"
    const val IS_INDIVIDUAL = "is_individual"
    const val STARTED_TIME = "started_time"
    const val ENDED_TIME = "ended_time"
    const val CALL_ID = "call_id"
    const val RECEIVER_ID = "receiver_id"
    const val IS_RECEIVER_DETAILS_AVAILABLE = "is_receiver_details_available"
    const val BALANCE_TIME = "balance_time"
    const val RECEIVER_NAME = "receiver_name"
    const val CALL_USER_ID = "call_user_id"
    const val NEED_TO_FINISH = "need_to_finish"
    const val REMAINING_TIME = "remaining_time"
}
